# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d3d404b9f6e97149dde8af44d867e33"
name = "section lift"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_themes,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
